import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { API } from "../App";
import { PageLayout } from "../components/layout/Layout";
import { Card, CardContent } from "../components/ui/card";
import axios from "axios";

export default function Disclaimer() {
  const [settings, setSettings] = useState({ brand_name: "LOVE-AI", company_name: "LOVE-AI Inc." });

  useEffect(() => {
    const fetchSettings = async () => {
      try {
        const response = await axios.get(`${API}/settings/site`);
        setSettings(prev => ({ ...prev, ...response.data }));
      } catch (error) {}
    };
    fetchSettings();
  }, []);

  return (
    <PageLayout>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12" data-testid="disclaimer-page">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="font-heading text-4xl font-bold mb-8">Disclaimer</h1>
          <p className="text-muted-foreground mb-8">Last updated: February 2025</p>
          
          <Card className="rounded-3xl border-border/50">
            <CardContent className="p-8 prose prose-sm dark:prose-invert max-w-none">
              <h2>1. General Disclaimer</h2>
              <p>The information and suggestions provided by {settings.brand_name} are for general informational and entertainment purposes only. Nothing on this service constitutes professional advice.</p>

              <h2>2. No Guarantee of Results</h2>
              <p className="font-semibold">Important: {settings.brand_name} does NOT guarantee:</p>
              <ul>
                <li>That you will find a romantic partner</li>
                <li>That our suggestions will lead to dates or relationships</li>
                <li>Success rates or match improvements</li>
                <li>That AI suggestions will be appropriate for every situation</li>
              </ul>

              <h2>3. AI-Generated Content</h2>
              <p>All suggestions, pickup lines, bio content, and feedback are generated by artificial intelligence. This content:</p>
              <ul>
                <li>May not always be accurate or appropriate</li>
                <li>Should be reviewed and edited before use</li>
                <li>Is provided as inspiration, not as definitive advice</li>
                <li>May occasionally contain errors or inappropriate suggestions</li>
              </ul>

              <h2>4. User Responsibility</h2>
              <p>You are solely responsible for:</p>
              <ul>
                <li>Reviewing all AI-generated content before using it</li>
                <li>Your interactions on dating platforms</li>
                <li>The accuracy of information you provide about yourself</li>
                <li>Complying with the terms of dating platforms you use</li>
                <li>Your personal safety when meeting people</li>
              </ul>

              <h2>5. Dating Safety</h2>
              <p>{settings.brand_name} is not a dating platform. We strongly recommend:</p>
              <ul>
                <li>Meeting in public places for first dates</li>
                <li>Telling someone where you're going</li>
                <li>Verifying identity before meeting</li>
                <li>Trusting your instincts about safety</li>
                <li>Reporting suspicious behavior to dating platforms</li>
              </ul>

              <h2>6. Not Professional Advice</h2>
              <p>Our service does not provide:</p>
              <ul>
                <li>Relationship counseling</li>
                <li>Psychological advice</li>
                <li>Legal advice</li>
                <li>Medical advice</li>
              </ul>
              <p>If you need professional help, please consult a qualified professional.</p>

              <h2>7. Third-Party Platforms</h2>
              <p>We are not affiliated with any dating platforms (Tinder, Bumble, Hinge, etc.). We do not:</p>
              <ul>
                <li>Have access to their systems or user data</li>
                <li>Guarantee compatibility with their platforms</li>
                <li>Take responsibility for your interactions on those platforms</li>
              </ul>

              <h2>8. Statistics and Claims</h2>
              <p>Any statistics, success rates, or claims displayed on our website are for illustrative purposes and may not reflect actual user results.</p>

              <h2>9. Limitation of Liability</h2>
              <p>{settings.company_name} and its affiliates shall not be liable for:</p>
              <ul>
                <li>Any damages resulting from use of our service</li>
                <li>Outcomes of your dating interactions</li>
                <li>Actions of people you meet through dating platforms</li>
                <li>Loss of data or service interruptions</li>
              </ul>

              <h2>10. Changes to Disclaimer</h2>
              <p>We may update this disclaimer at any time. Continued use of the service constitutes acceptance of any changes.</p>

              <h2>11. Contact Us</h2>
              <p>If you have questions about this disclaimer, contact us at: {settings.contact_email || "support@love-ai.com"}</p>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </PageLayout>
  );
}
